version: 2

models:


  # =========================================
  # DIMENSION MODELS
  # =========================================

  - name: dim_zones
    description: Taxi zone dimension

    columns:
      - name: location_id
        description: Unique zone ID
        data_tests:
          - not_null

  - name: dim_vendors
    description: Taxi vendor dimension

    columns:
      - name: vendor_id
        description: Unique vendor ID
        data_tests:
          - not_null

  # =========================================
  # FACT MODELS
  # =========================================

  - name: fct_trips
    description: Fact table containing taxi trip information

    config:
      contract:
        enforced: true

    columns:

      - name: trip_id
        description: Unique trip identifier
        data_type: string
        data_tests:
          - not_null

      - name: service_type
        description: Taxi service type
        data_type: string
        data_tests:
          - accepted_values:
              arguments:
                values: ['Green', 'Yellow']

      - name: vendor_id
        description: Taxi vendor ID
        data_type: integer

      - name: pickup_location_id
        description: Pickup TLC zone ID
        data_type: integer

      - name: dropoff_location_id
        description: Dropoff TLC zone ID
        data_type: integer

      - name: pickup_datetime
        description: Pickup timestamp
        data_type: timestamp

      - name: dropoff_datetime
        description: Dropoff timestamp
        data_type: timestamp

      - name: passenger_count
        description: Number of passengers
        data_type: integer

      - name: trip_distance
        description: Distance traveled in miles
        data_type: numeric

      - name: total_amount
        description: Total trip amount
        data_type: numeric

      - name: payment_type
        description: Payment type code
        data_type: integer

      - name: payment_type_description
        description: Payment type description
        data_type: string

        